version: '3'

tasks:
  build:
    cmds:
      - task: build-server
      - task: build-client
      - task: build-pacman
      - task: build-extension
  
  build-client:
    dir: 'client'
    sources: 
      - '**/*.ts'
    cmds:
      - npm install 
      - npm run build
    generates:
      - dist/index.html
    method: timestamp
  
  build-server:
    sources: 
      - '**/*.go'
    cmds:
      - ./build.sh
    generates:
      - bin/serve
    method: timestamp

  build-pacman:
    dir: 'pacman'
    sources:
      - '**/*.ts'
      - '**/*.json'
    cmds:
      - npm run build
      - rsync -avz --delete dist/ ~/downloads/pacman
    generates:
      - dist/manifest.json
    method: timestamp

  build-extension:
    dir: 'extension'
    sources:
      - '**/*.ts'
      - '**/*.json'
    cmds:
      - npm run build 
      - rsync -avz --delete dist/ ~/downloads/dev-world
    generates:
      - dist/manifest.json
    method: timestamp
